### ISSUE TITLE
4.0.0-1: context.cmdFormatter & start.format is not a function

### ISSUE THREAD

**Issue by fullstackfool** [CroudTech/vue-fullcalendar#172]
We've been using eventSources like:

```
{
          events({start, end, timeZone}, callback) {
            self.$http.get(`/holidays`, {
                timezone: timezone,
                start: start.format('YYYY/MM/DD')
            }).then(response => {
              callback(response.data.data)
            })
          },
          color: 'yellow',
          textColor: 'black',
},
```

Recently receiving errors of `start.format is not a function`. 

Logging `start` shows it to be an object:
```
{
    end: Sun Nov 11 2018 00:00:00 GMT+0000 (Greenwich Mean Time) {}
    endStr: "2018-11-11T00:00:00Z"
    start: Sun Sep 30 2018 00:00:00 GMT+0100 (British Summer Time) {}
    startStr: "2018-09-30T00:00:00+01:00"
    timeZone: "local"
}
```

`end`:
```
f ( ) {
        if (!isResolved) {
            isResolved = true;
            success.apply(this, arguments);
        }
}
```

If i fix the format issue by updating to:
```
{
          events({start, end, timeZone}, callback) {
            self.$http.get(`/holidays`, {
                start: moment(start).format('YYYY/MM/DD'), 
                timezone: timezone
            }).then(response => {
              callback(response.data.data)
            })
          },
          color: 'yellow',
          textColor: 'black',
},
```

Then we get a new error: `TypeError: context.cmdFormatter is not a function`

Versions:
vue-full-calendar: `4.0.0-1`
fullcalendar: `4.0.0-alpha.2`
moment: `2.22.2`
moment-timezone: `0.5.21`

I suspect we've changed another dependacy, which in turn has effected fullcalendar, but i can't figure out what. Does this error look familiar to anyone?

**Comment by fullstackfool** [comment]
Invalid object.

Tracked the issue to when vue-full-calendar is using `full-calendar: 4.0.0-alpha.2`. Forcing it to use `4.0.0-alpha` fixes the issue.

**Comment by ash-rain** [comment]
+1 Subscribing. Having the same issue with the new alpha.

**Comment by BrockReece** [comment]
I am guessing then this is probably an error with `fullcalendar: 4.0.0-alpha.2` rather than this repo. Is it worth opening an issue on their repo?

I am happy to fix the version of fullcalendar though to the more stable version if this is a blocker?

**Comment by BrockReece** [comment]
I am reading their release notes for v4, it looks like there is a section outlining some changes in 'Event Source Function'

Have you read the [docs](https://fullcalendar.io/docs/v4/events-function)?
Seems like the `fetchInfo` obj has some additional fields for `startStr` and `endStr`. Are they worth trying?

**Comment by JackPriceBurns** [comment]
It seems the first argument is this fetchInfo object that has both the start and the end date time stamps. The start and end are no longer passed separately? And the other arguments seem to return promises, not sure what they do.

**Comment by fullstackfool** [comment]
Quite possibly - looking into it now.

The fixed version would be a good temporary fix, thanks!

**Comment by fullstackfool** [comment]
Yeah, so the events have been combined, which you can then use to instantiate a moment object.

Then we get a new error: `TypeError: context.cmdFormatter is not a function`

Now going to try using an event url, instead of the function

**Comment by identy** [comment]
// titleFormat: 'MMMM'

error in title format

**Comment by Xalior** [comment]
This bug still exists in the final release of fullcal, and is in the base library itself outwith of the vue integrations it seems (I can reproduce it on the base library, exact same issues as @fullstackfool reports above)

**Comment by Herz3h** [comment]
Same issue here, just upgraded to fullCalendar 5, I'm using @fullcalendar/moment plugin to format dates. When I switch from dayGridMonth to dayGridWeek, this errors shows up:

```
preact.module.js:15 Uncaught TypeError: context.cmdFormatter is not a function
    at CmdFormatter.format (main.js:1599)
    at DateEnv.format (main.js:4119)
    at Object.eval [as children] (main.js:227)
    at d.Consumer [as constructor] (preact.module.js:15)
    at d.L [as render] (preact.module.js:15)
    at T (preact.module.js:15)
    at g (preact.module.js:15)
    at T (preact.module.js:15)
    at g (preact.module.js:15)
    at j (preact.module.js:15)
```

After inspection cmdFormatter has a `null` value.
